@if "%DEBUG%" == "" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows - updated for Android 12
@rem
@rem  CHANGES FOR ANDROID 12:
@rem   1. Added Java 11+ version check - Android Gradle Plugin 4.2.2
@rem      and Gradle 7.4.2 require Java 11+. Without this check, running
@rem      with Java 8 gives a confusing "Unsupported class file major
@rem      version" error. This script now checks and prints a clear error.
@rem
@rem   2. Increased DEFAULT_JVM_OPTS memory - Android 12 builds with
@rem      compileSdk 33 and R8 full mode require more heap memory.
@rem      Changed from empty to: -Xmx2048m -Xms512m -XX:MaxMetaspaceSize=512m
@rem
@rem   3. The gradle-wrapper.properties file (already updated) points to
@rem      Gradle 7.4.2, which is required for Android 12 API compilation.
@rem
@rem  NOTE: This script is auto-generated by Gradle. The changes above
@rem  are the only modifications needed for Android 12 compatibility.
@rem  The script itself is a simple launcher that downloads and runs the
@rem  Gradle version specified in gradle/wrapper/gradle-wrapper.properties.
@rem
@rem  On Windows, you MUST run this from a cmd.exe or PowerShell window
@rem  that has Java 11+ in its PATH or has JAVA_HOME set to JDK 11+.
@rem
@rem  Recommended JDK download: https://adoptium.net/ (Eclipse Temurin 11 or 17)
@rem
@rem ##########################################################################

@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%" == "" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem ============================================================
@rem Android 12: increased JVM heap for large builds
@rem Android Gradle Plugin 4.2.2 + R8 full mode + compileSdk 33
@rem requires more memory than older builds. Without this, the
@rem build fails with "Java heap space" OutOfMemoryError.
@rem ============================================================
set DEFAULT_JVM_OPTS=-Xmx2048m -Xms512m -XX:MaxMetaspaceSize=512m

@rem ============================================================
@rem Android 12: Java version check
@rem Android Gradle Plugin 4.2.2 requires Java 11+.
@rem Gradle 7.4.2 requires Java 11+.
@rem Java 8 will cause the build to fail with:
@rem   "Unsupported class file major version 61"
@rem ============================================================

@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if "%ERRORLEVEL%" == "0" goto checkJavaVersion

echo.
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.
echo For Android 12 builds, you need JDK 11 or later.
echo Download from: https://adoptium.net/ (Eclipse Temurin 11 or 17)
echo.
goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto checkJavaVersion

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.
echo For Android 12 builds, you need JDK 11 or later.
echo Download from: https://adoptium.net/ (Eclipse Temurin 11 or 17)
echo.
goto fail

:checkJavaVersion
@rem ============================================================
@rem Android 12: extract the Java major version and verify >= 11
@rem ============================================================
for /f tokens^=2-5^ delims^=."_ " %%a in ('"%JAVA_EXE%" -version 2^>^&1 ^| find "version"') do (
    set JAVA_MAJOR_VERSION=%%a
)
if "%JAVA_MAJOR_VERSION%" == "" set JAVA_MAJOR_VERSION=0

if %JAVA_MAJOR_VERSION% LSS 11 (
    echo.
    echo ERROR: Java 11 or higher is required for Android 12 builds.
    "%JAVA_EXE%" -version
    echo.
    echo Current Java version: %JAVA_MAJOR_VERSION%
    echo Please install JDK 11 or later and set JAVA_HOME to point to it.
    echo Download from: https://adoptium.net/ (Eclipse Temurin 11 or 17)
    echo.
    goto fail
)

:init
@rem Get command-line arguments, handling Windows variants

if not "%OS%" == "Windows_NT" goto win9xME_args

:win9xME_args
@rem Slurp the command line arguments.
set CMD_LINE_ARGS=
set _SKIP=2

:win9xME_args_slurp
if "x%~1" == "x" goto execute

set CMD_LINE_ARGS=%*

:execute
@rem Setup the command line

set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar

@rem Execute Gradle
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %CMD_LINE_ARGS%

:end
@rem End local scope for the variables with windows NT shell
if "%ERRORLEVEL%"=="0" goto mainEnd

:fail
rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
rem the _cmd.exe /c_ return code!
if  not "" == "%GRADLE_EXIT_CONSOLE%" exit 1
exit /b 1

:mainEnd
if "%OS%"=="Windows_NT" endlocal

:omega
